# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: x3plus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'x3plus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cx3plus.proto\x12\x06x3plus\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"E\n\x1aSingleJointPositionRequest\x12\x12\n\njoint_name\x18\x01 \x01(\t\x12\x13\n\x0bjoint_value\x18\x02 \x01(\x05\"-\n\x1bSingleJointPositionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xb0\x01\n\x11RosmasterServices\x12\x36\n\x08SayHello\x12\x14.x3plus.HelloRequest\x1a\x12.x3plus.HelloReply\"\x00\x12\x63\n\x16SetSingleJointPosition\x12\".x3plus.SingleJointPositionRequest\x1a#.x3plus.SingleJointPositionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'x3plus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=24
  _globals['_HELLOREQUEST']._serialized_end=52
  _globals['_HELLOREPLY']._serialized_start=54
  _globals['_HELLOREPLY']._serialized_end=83
  _globals['_SINGLEJOINTPOSITIONREQUEST']._serialized_start=85
  _globals['_SINGLEJOINTPOSITIONREQUEST']._serialized_end=154
  _globals['_SINGLEJOINTPOSITIONRESPONSE']._serialized_start=156
  _globals['_SINGLEJOINTPOSITIONRESPONSE']._serialized_end=201
  _globals['_ROSMASTERSERVICES']._serialized_start=204
  _globals['_ROSMASTERSERVICES']._serialized_end=380
# @@protoc_insertion_point(module_scope)
