# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import x3plus_pb2 as x3plus__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in x3plus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RosmasterServicesStub(object):
    """The RosmasterServices definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getJointPositionArray = channel.unary_unary(
                '/x3plus.RosmasterServices/getJointPositionArray',
                request_serializer=x3plus__pb2.Empty.SerializeToString,
                response_deserializer=x3plus__pb2.JointPosititonArray.FromString,
                _registered_method=True)
        self.setJointPositionArray = channel.unary_unary(
                '/x3plus.RosmasterServices/setJointPositionArray',
                request_serializer=x3plus__pb2.JointPosititonArray.SerializeToString,
                response_deserializer=x3plus__pb2.ResultResponse.FromString,
                _registered_method=True)
        self.setJointPositionSingle = channel.unary_unary(
                '/x3plus.RosmasterServices/setJointPositionSingle',
                request_serializer=x3plus__pb2.SingleJointPositionRequest.SerializeToString,
                response_deserializer=x3plus__pb2.ResultResponse.FromString,
                _registered_method=True)


class RosmasterServicesServicer(object):
    """The RosmasterServices definition.
    """

    def getJointPositionArray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setJointPositionArray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setJointPositionSingle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RosmasterServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getJointPositionArray': grpc.unary_unary_rpc_method_handler(
                    servicer.getJointPositionArray,
                    request_deserializer=x3plus__pb2.Empty.FromString,
                    response_serializer=x3plus__pb2.JointPosititonArray.SerializeToString,
            ),
            'setJointPositionArray': grpc.unary_unary_rpc_method_handler(
                    servicer.setJointPositionArray,
                    request_deserializer=x3plus__pb2.JointPosititonArray.FromString,
                    response_serializer=x3plus__pb2.ResultResponse.SerializeToString,
            ),
            'setJointPositionSingle': grpc.unary_unary_rpc_method_handler(
                    servicer.setJointPositionSingle,
                    request_deserializer=x3plus__pb2.SingleJointPositionRequest.FromString,
                    response_serializer=x3plus__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'x3plus.RosmasterServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('x3plus.RosmasterServices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RosmasterServices(object):
    """The RosmasterServices definition.
    """

    @staticmethod
    def getJointPositionArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x3plus.RosmasterServices/getJointPositionArray',
            x3plus__pb2.Empty.SerializeToString,
            x3plus__pb2.JointPosititonArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setJointPositionArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x3plus.RosmasterServices/setJointPositionArray',
            x3plus__pb2.JointPosititonArray.SerializeToString,
            x3plus__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setJointPositionSingle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x3plus.RosmasterServices/setJointPositionSingle',
            x3plus__pb2.SingleJointPositionRequest.SerializeToString,
            x3plus__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
